# The initial policy to use for the comparator
initial_policy: "flat"

# The policies to use for the comparator
policies:
  flat:
    model_path: "Models/Onnx/aug_act_net_QuaidSIM-Flat_RA-TD3_+337.452_400099.onnx"
  ramp:
    model_path: "Models/Onnx/aug_act_net_QuaidSIM-Ramp_RA-TD3_+337.452_400099.onnx"
  uneven:
    model_path: "Models/Onnx/aug_act_net_QuaidSIM-Uneven_RA-TD3_+348.233_400099.onnx"

# The path to the trained GRU model in PyTorch format and ONNX format
embedding_gru:
  pth_path: "Models/Base/trained_model_GRU.pth"
  onnx_path: "Models/Onnx/aug_trained_model_GRU_state_only.onnx"

# The path to the comparator database
comparator_database_path: "Models/Comparator/comparator_database.npz"

# The UMAP model to use for the comparator
umap:
  kind: "standard" # or can be 'parametric_onnx'
  path: "Models/Umap/selector_umap.pkl"